### ISSUE TITLE
Rolling release

### ISSUE THREAD

**Issue by pablogs9** [micro-ROS/micro_ros_setup#253]
This issue reports all repos involved in micro-ROS Rolling release migration:

| Repo                                      | Rolling branch                                                                 | Status                                                                                                                                    |
| ----------------------------------------- | ------------------------------------------------------------------------------ | ----------------------------------------------------------------------------------------------------------------------------------------- |
| micro-ROS/micro_ros_setup                 | [main](https://github.com/micro-ROS/micro_ros_setup/tree/main)                 | ![Nightly](https://github.com/micro-ROS/micro_ros_setup/workflows/Nightly/badge.svg)                                                      |
| micro-ROS/rcl                             | [master](https://github.com/micro-ROS/rcl/tree/master)                         | ![micro-ROS fork Update Checker](https://github.com/micro-ROS/rcl/workflows/micro-ROS%20fork%20Update%20Checker/badge.svg)                |
| micro-ROS/rcutils                         | [master](https://github.com/micro-ROS/rcutils/tree/master)                     | ![micro-ROS fork Update Checker](https://github.com/micro-ROS/rcutils/workflows/micro-ROS%20fork%20Update%20Checker/badge.svg)            |
| micro-ROS/rosidl_typesupport              | [master](https://github.com/micro-ROS/rosidl_typesupport/tree/master)          | ![micro-ROS fork Update Checker](https://github.com/micro-ROS/rosidl_typesupport/workflows/micro-ROS%20fork%20Update%20Checker/badge.svg) |
| micro-ROS/micro-ROS-demos                 | [main](https://github.com/micro-ROS/micro-ROS-demos/tree/main)                 |                                                                                                                                           |
| micro-ROS/rosidl_typesupport_microxrcedds | [main](https://github.com/micro-ROS/rosidl_typesupport_microxrcedds/tree/main) |                                                                                                                                           |
| micro-ROS/rmw-microxrcedds                | [main](https://github.com/micro-ROS/rmw-microxrcedds/tree/main)                |                                                                                                                                           |
| micro-ROS/nuttx_apps                      | Pending                                                                        |                                                                                                                                           |
| micro-ROS/freertos_apps                   | [main](https://github.com/micro-ROS/freertos_apps/tree/main)                   |                                                                                                                                           |
| micro-ROS/raspbian_apps                   | [main](https://github.com/micro-ROS/raspbian_apps/tree/main)                   |                                                                                                                                           |
| micro-ROS/micro-ROS-Agent                 | Pending                                                                        |                                                                                                                                           |
| micro-ROS/zephyr_apps                     | [main](https://github.com/micro-ROS/zephyr_apps/tree/main)                     |                                                                                                                                           |
| micro-ROS/ros_tracing                     | [master](https://gitlab.com/ros-tracing/ros2_tracing/-/tree/master)            |                                                                                                                                           |
| micro-ROS/microros-github.io              | --                                                                             |                                                                                                                                           |
| micro-ROS/docker                          | [main](https://github.com/micro-ROS/docker/tree/main)                          |                                                                                                                                           |
| micro-ROS/micro_ros_espidf_component      | [main](https://github.com/micro-ROS/micro_ros_espidf_component/tree/main)      | ![Nightly](https://github.com/micro-ROS/micro_ros_espidf_component/workflows/Nightly/badge.svg)                                           |
| micro-ROS/micro_ros_zephyr_module         | [main](https://github.com/micro-ROS/micro_ros_zephyr_module/tree/main)         | ![Nightly](https://github.com/micro-ROS/micro_ros_zephyr_module/workflows/Nightly/badge.svg)                                              |
| micro-ROS/micro_ros_arduino               | [main](https://github.com/micro-ROS/micro_ros_arduino/tree/main)               | ![Library generator](https://github.com/micro-ROS/micro_ros_arduino/workflows/Library%20generator/badge.svg)                              |

# TODO

## Upgrade forks to ROS 2 main
The following repos should rebase their main on ROS2 main branch:
- [x] micro-ROS/rcl
- [x] micro-ROS/rcutils 
- [x] micro-ROS/rosidl_typesupport 
- [x] micro-ROS/ros_tracing
  - [x] Evaluate if tracing should be used in micro-ROS: Works with master

## Middleware

- [x] Check and implement changes in RMW API

## Maintain ROS 2 forks

- [x]  A daily mechanism should be integrated into Github CI to detect ROS 2 heads that are above micro-ROS forks in `foxy` and `rolling/main`
    - [x] Added fork checker to:
         - https://github.com/micro-ROS/rcl/actions/
         - https://github.com/micro-ROS/rcutils/actions/
         - https://github.com/micro-ROS/rosidl_typesupport/actions/
- [ ]  PR should be created to get rid of these forks

## Builds

The following tools **should work** and have a **daily build check** with the `rolling/main` versions of:
- [x] micro_ros_setup
- [x] micro_ros_espidf_component
- [x]  micro_ros_zephyr_module
- [x]  micro_ros_arduino

## Testing

The following demos and examples should be tested and working:
- [ ] freertos_apps
- [ ]  raspbian_apps
- [ ]  nuttx_apps
- [x]  zephyr_apps
- [x]  micro-ROS-demos (Integration tests here?)

## MISC

- [ ] All occurrences of `std_msgs` need to be changed, since it's deprecated

## Future work
- [x] Add Nuttx 10
- [x] Explore Mbed
    - We should integrate with Mbed as an external library, once the static lib is built CMake will be in charge of linking. But, how can we extract the toolchain for static building?

**Comment by pablogs9** [comment]
Regarding branch naming convention:

We are going to use `main` as micro-ROS Rolling branch in all repos in order to follow ROS 2 guidelines.

**Comment by pablogs9** [comment]
## Minor TODOs

A list with minor changes and improvements that allow repo cleaning:
- [ ]  Comment [this line](https://github.com/micro-ROS/micro_ros_setup/blob/0788fa566a870d1ebdc25834323500133e6003fd/config/client_ros2_packages.txt#L2) and avoid [this](https://github.com/micro-ROS/micro_ros_setup/blob/0788fa566a870d1ebdc25834323500133e6003fd/config/freertos/olimex-stm32-e407/create.sh#L18)
